executor:
  corePoolSize:  1
  maxPoolSize:   3
  queueCapacity: 20
  threadNamePrefix: "StdPrefix-"

graphite:
  server: localhost
  port: 2003
  prefix: ${groupId}-${artifactId}-${spring.profiles.active}

endpoints:
  prometheus:
    id: prometheus
    sensitive: false
    enabled: true

application:
  name: ${artifactId}